language: rust
rust:
  - stable
  - beta
  - nightly

before_install:
  - sudo apt-get update
  - sudo apt-get install libzmq3-dev
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
